layout_spectrum: 0.2138762
typography_spectrum: 0.9468664
color:
  saturation: 0.9397664
  lightness: 0.163118
  brandStrength: 0.7708478
  rhythmicContrast: 0.3449939
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Für Silvan
